# Generated by Django 5.1.3 on 2024-12-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userbase_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='postcode',
        ),
    ]
