# Generated by Django 5.1.3 on 2024-12-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSelections',
        ),
    ]
